<?php

namespace AppBundle\Repository;

/**
 * AccessHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
