<?php

namespace AppBundle\Repository;

/**
 * CompanyProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
