<?php

namespace AppBundle\Repository;

/**
 * CreditProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditProductRepository extends \Doctrine\ORM\EntityRepository
{
}
