<?php

namespace AppBundle\Repository;

/**
 * OperationHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
